### ISSUE TITLE
acts-as-taggable-on gem dilemma: To replace with my own tag model or to modify its gem

### ISSUE THREAD

**Issue by awongCM** [refinery/refinerycms-blog#387]
Not long ago, I made a feature request on having a tag administration function as part of its blog engine, just like you would administer and manage your blog posts, comments, categories etc.

I learnt that acts-as-taggable-on gem is one of those dependencies listed in the gemspec and thought I would like to know how its internal mechanism actually works.

But before I continue discussing about this gem, I want to firstly discuss my original plan of developing my feature.

In my rspec test converage, I started off working like this.
```ruby
# encoding: utf-8
require 'spec_helper'
require 'pry-rails'

describe "Tags admin" do
  refinery_login_with :refinery_user

  let(:name) { "opentag" }

  it "can create tags" do
    visit refinery.admin_root_path

    within("nav#menu") { click_link "Blog" }
    within("nav.multilist") { click_link "Create new tag" }

    fill_in "Title", :with => name
    click_button "Save"

    tag = Refinery::Blog::Tag.first
    tag.name.should eq(name)
  end

  it "can manage tags" do
    visit refinery.admin_root_path

    within("nav#menu") { click_link "Blog"}
    within("nav.multilist") {click_link "Manage tags"}

    visit refinery.blog_admin_tags_path


  end

end
```
 
And this rspec file looks somewhat similar to the categories rspec.

In that line

```ruby
tag = Refinery::Blog::Tag.first
```

I thought about making my own Tag model under such namespace after reading the link below (just like `Refinery::Blog:Categories` etc ).  

http://railscasts.com/episodes/382-tagging

With this, I thought about replacing the acts-as-taggable-on gem(and removing it from gemspec file) with this.  I want to emulate the similar admin functions for this just like what you currently have for managing categories, as part of its business use case.

But as I went away and trying to figuring its feasibility within refinery-blog environment, I stumbled upon an interesting challenge that involves plenty of refactoring around the tagging ruby gem.  I realised there are many unit testing instances that rely on tagging ruby gem a lot.

Thus I started to wonder whether my original proposal to replace the gem with my own tag model still be feasible or not to pull off.  Cause I don't know what would be the major consequence of modifying all the test instances, routes, engines etc should this proposed change comes drastic.

Thus which brings me back to the original discussion on the pros and cons of replacing the gem and modifying the gem.

On one hand, if I decide to replace the gem with my own tag model, then there's going to be a lot of refactoring grunt work, not even including the times it takes to complete and pass the tests.  I imagined it will take a lot of time??

On the other hand, if I decide to modify (or hack) the gem instead, which will be the safer option, less refactoring, but then my new rspec tag tests file would have to begin like this.

```ruby
tag = ActsAsTaggableOn:Tag:first
```

This may work favourably you may think.  But then I personally don't like this because this will break the rest of the coding conventions of Refinery CMS already.  So surely this can't be a good coding practice, can it?

Hence my dilemma..

Would anyone care to join me to discuss this matter at hand what should I do to handle this?

**Comment by awongCM** [comment]
Hey @parndt 

I'm just catching up on this old ticket that's been sitting here for some time.

Last time we discussed was to set up an abstract Adapter class that implements several important methods of ActAsTaggableOn activerecord.  So I went back into it and revised my code a bit, such as the following.

<b>tags_spec.rb<b>

    require 'spec_helper'

    describe "Tags admin" do
      refinery_login_with :refinery_user

      let(:name) { "opentag" }

      it "can create tags" do
        visit refinery.admin_root_path

       within("nav#menu") { click_link "Blog" }
       within("nav.multilist") { click_link "Create new tag" }

       visit refinery.new_blog_admin_tag_path
       ............
       ............
      .............
       
      end
    end

<b>my own adapterclass for ActsAsTaggableOn::Tag<b>

    module Refinery
        module Blog
            class Tag < ActsAsTaggableOn::Tag

             def initialize(object)
                  super
                  @object = object
              end

             ###All of ActsAsTaggable inteface methods goes here

            end
        end
    end

<b>TagsController Class<b>

    module Refinery
      module Blog
        module Admin
          class TagsController < ::Refinery::AdminController

            def new
                @tag = Refinery::Blog::Tag.new(ActsAsTaggableOn::Tag.new(params[:name]))
                render :new
            end

          end
        end
      end
    end

I ran the 'bundle exec rspec'.  I got the following error

    Failures:

      1) Tags admin can create tags
         Failure/Error: within("nav.multilist") { click_link "Create new tag" }
         ArgumentError:
           When assigning attributes, you must pass a hash as an argument.
         # ./app/models/refinery/blog/tag.rb:10:in `initialize'
         # ./app/controllers/refinery/blog/admin/tags_controller.rb:14:in `new'
         # ./spec/features/refinery/blog/admin/tags_spec.rb:15:in `block (3 levels) in <top (required)>'
         # ./spec/features/refinery/blog/admin/tags_spec.rb:15:in `block (2 levels) in <top (required)>'

The small change I did was that I inherited my tags adapter class from the ActsAsTaggableOn::Tag ActiveRecord class so that it could be initialized as Tag ActiveRecord and this class would be one I can use to interact with the ActsAsTaggable class methods.   After refactoring the code a bit, the above error mentions that I did not properly pass a hash as an argument to Tag adapter class.  But in my tag_controller class.  I specified

    @tag = Refinery::Blog::Tag.new(ActsAsTaggableOn::Tag.new(params[:name]))

with params[:name] as the hash into ActsAsTaggableOn::Tag class, and then the same class is used for the my Refinery::Blog:Tag adapter class to initialize the record.

So why do I still need to pass the hash argument within my adapter class here again?

Let me know your thoughts on it as soon as you come available. 

Cheers!

**Comment by parndt** [comment]
You're overriding the `initialize` method to take an object instead of a hash, and then you're calling `super` which implicitly means `super(object)`, which is not the hash that `ActsAsTaggableOn` is expecting.

**Comment by awongCM** [comment]
Oh.  Okay.

Thanks @parndt.  I had no idea having the <b>super</b> keyword on its own, has the implied invocation to use its own default parameters during its initialization at run-time.  

which means under my adapter class I have to rewrite it as follows.

    def initialize(object)
         super object.name
         @object = object
    end

which now works - of course.  

Though, now that I'm looking at it, I find that this type of adapter setup looks little silly to you, don't you think?

**Comment by parndt** [comment]
It may look silly, but if it shields us from changes or breakages then it may be worth it?

**Comment by bricesanchez** [comment]
Could i close this issue ?

**Comment by awongCM** [comment]
Hi.

Wow.  It sure has been a long while since my last contribution to the open source community..

Sorry for being inactive for so long.

Haven't the chance to work on Ruby for a while.  Been focusing on JS these days.

You may close it.  I will just have to open up a new issue when I'm ready to get back into Ruby again.

**Comment by bricesanchez** [comment]
Thanks for your answer.
