### ISSUE TITLE
Rspec ActAsTaggable Error - issue related with issue #387

### ISSUE THREAD

**Issue by awongCM** [refinery/refinerycms-blog#410]
On #387, I've finally managed to make some progress further with my tags spec.

I can see some of my tests are properly passing/failing as I write them.

So here's the latest confusing problem I couldn't understand why it wouldn't work.

in my <b>tags_spec.rb<b>

    require 'spec_helper'

    describe "Tags admin" do
      refinery_login_with :refinery_user
        
        #######################
        it "can manage tags" do
            visit refinery.admin_root_path

            within("nav#menu") { click_link "Blog"}
            within("nav.multilist") {click_link "Manage tags"}

          end

          context "when there are some tags" do
             let!(:tags) { Refinery::Blog::Tag.all  }
             before { visit refinery.blog_admin_tags_path }

             it "should say there's at least one tag on the page" do
               tags.size.should be >= 1
               page.should have_content("There are some tags on the page")
             end
          end

          context "when there are no tags" do
             before do
                subject.class.delete_all
                visit refinery.blog_admin_tags_path
             end

             it "should say there are not tags on the page" do
                page.should have_content("There are no tags on the page")
             end
          end

    end

What this testing section does is that I have a blog administrator who can manage any tags he created/updated/deleted on a tag management page.  Thus I'm describing him the steps in navigation the pages to manage tags updates.  

In the context "when there are some tags" section, I used the let helper to define an instance variable of my Tags adapter class to retrieve all existing tag records in the db before I visit the main index tag page.  Thus I expect to have the tags record to have at least one record as part of the requirement to pass this test.

And certainly do have an one existing Tag record when I ran `rails console` and discover that `Refinery::Blog:Tag.all` has one record in it (which I inserted manually earlier).

But after running rspec,

    bundle exec rspec spec/features/refinery/blog/admin/tags_spec.rb
    Run options: include {:focus=>true}

    All examples were filtered out; ignoring {:focus=>true}
    ..FF

    Failures:

      1) Tags admin when there are some tags should say there's at least one tag on the page
         Failure/Error: tags.size.should be >= 1
           expected: >= 1
                got:    0
         # ./spec/features/refinery/blog/admin/tags_spec.rb:42:in `block (3 levels) in <top (required)>'

It tells me there is no record in `Refinery::Blog::Tag.all` as specified in my let! predicate - at all.  How can this be when I tested this in rails console earlier????

**Comment by awongCM** [comment]
Has anyone had the chance to look into this issue?

**Comment by parndt** [comment]
You haven't actually created any tags in your spec.. remember that `rails console` shows your `development` database and `rspec` is using your `test` database.

**Comment by awongCM** [comment]
Thanks @parndt.  So how I do pass my spec in the <b>when there are some tags</b> context section?    Do I need to use something like FactoryGirl to set up a dummy test record in order to make this work?

**Comment by parndt** [comment]
Yep, that's exactly what you need to do. We may not already have a Tag factory, in which case you'll need to define one under `spec/factories/`

**Comment by awongCM** [comment]
Fantastic.

Will do.

Cheers!
