### ISSUE TITLE
Remove Settings UI

### ISSUE THREAD

**Issue by bricesanchez** [refinery/refinerycms-blog#425]
Hello all !

I would like to suggest to remove those links : 
https://github.com/refinery/refinerycms-blog/blob/master/app/views/refinery/blog/admin/_submenu.html.erb#L67-L89

I prefer to manage configuration in the blog initializer instead of an UI.

What do you think of that ?

**Comment by parndt** [comment]
It's fine with me, then maybe we wouldn't need to depend on refinerycms-settings?

**Comment by anitagraham** [comment]
Really? But we're devs who are happy with initializers. What about clients? Wouldn't they want to manage these things themselves?  Just asking.

**Comment by parndt** [comment]
I quite like them being in the UI personally.. On older sites I can just disable comments without re deploying.

**Comment by bricesanchez** [comment]
It's a little confusing to have configs in an initializer, in settings ul list links and in refinerycms-settings.

Personnally, i prefer to have all in an initializer, it's faster to review and clone config. 

Many of my customers doesn't know what to do with those settings and are afraid to change them.

I think we should keep refinery simple for end user. No settings in UI == no mistakes.

**Comment by anitagraham** [comment]
I think you have to cater for more sophisticated customers as well. 
Perhaps the option to expose blog settings into refinerycms-settings should be an option for the developer?
@bricesanchez , where is the 'settings ul list links' you mention?

**Comment by bricesanchez** [comment]
> I think you have to cater for more sophisticated customers as well. 

I'm sorry but this is not an argument.

For developper, i think all options should be in a config initializer. i've been working on TYPO3 and Drupal and it's horrible how many configurations there are in UI.

> @bricesanchez , where is the 'settings ul list links' you mention?

See my first comment issue, all this discussion is about  thoses links : 
https://github.com/refinery/refinerycms-blog/blob/master/app/views/refinery/blog/admin/_submenu.html.erb#L67-L89

:)

**Comment by bricesanchez** [comment]
Sorry, I don't think removing settings UI is a good idea anymore.
