### ISSUE TITLE
Backend.css no longer compatible with RefineryCMS edge

### ISSUE THREAD

**Issue by darmens** [refinery/refinerycms-blog#434]
On a new installation when I try to access `/refinery/blog/posts`, even on the dummy app, I get this error:

## Sprockets::Rails::Helper::AssetFilteredError in Refinery::Blog::Admin::Posts#index
```
Completed 500 Internal Server Error in 429ms (ActiveRecord: 4.1ms)

ActionView::Template::Error (Asset filtered out and will not be served: add `Rails.application.config.assets.precompile += %w( refinery/blog/backend.css )` to `config/initializers/assets.rb` and restart your server):
    90: 
    91: </nav>
    92: 
    93: <% content_for :stylesheets, stylesheet_link_tag('refinery/blog/backend') %>
  sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:193:in `check_errors_for'
  sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:159:in `block in stylesheet_link_tag'
  sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:158:in `map'
  sprockets-rails (2.2.4) lib/sprockets/rails/helper.rb:158:in `stylesheet_link_tag'
```

Adding `Rails.application.config.assets.precompile += %w( refinery/blog/backend.css )` to `config/initializers/assets.rb` as suggested fixes the problem, but it seems that `backend.css` is no longer compatible with **RefineryCMS** as the backend looks like this:

![screenshot 2015-05-07 15 02 09](https://cloud.githubusercontent.com/assets/794154/7515779/3f9c8c56-f4ca-11e4-926f-f49719e44bfb.png)

I can update `backend.css` but I wouldn't know how to fix the sprockets error.

**Comment by dougbradbury** [comment]
:+1: I am experiencing the same thing.

**Comment by anitagraham** [comment]
A PR (#432) has been submitted for this, but the tests are failing.  I will look at the tests as some changes are needed when the icons are used.

**Comment by anitagraham** [comment]
OK, so icon fixes are in the works. I'll add the change I think is needed for the backend.css to be precompiled.

**Comment by parndt** [comment]
@anitagraham you mean like 7b6ae1eca13ff120d5abd9816d7c22f339d52e2e in #438?

**Comment by anitagraham** [comment]
Oh yes, just like that. Hadn't seen it.

**Comment by bricesanchez** [comment]
It works for me since #438.

Could i close this issue @darmens ?

**Comment by darmens** [comment]
yep, it works better!

Now it looks like this:

![screenshot 2015-06-16 16 37 13](https://cloud.githubusercontent.com/assets/794154/8185661/f436c218-1445-11e5-9893-01121c652281.png)
