### ISSUE TITLE
Post tags are merged together on update

### ISSUE THREAD

**Issue by darmens** [refinery/refinerycms-blog#436]
This happens only with refinerycms edge.
On post edit, the tags are loaded in the tags field without the commas, so when the user hits "save" the tags are merged together.

This is how to replicate it:
On a new installation fire up the dummy app and create a blog post with some tags:

![screenshot 2015-05-07 19 13 46](https://cloud.githubusercontent.com/assets/794154/7521343/687244cc-f4ed-11e4-95d8-8239a5bcbab2.png)

Save, and reopen the same post on edit:

![screenshot 2015-05-07 19 15 03](https://cloud.githubusercontent.com/assets/794154/7521361/8fe55a8a-f4ed-11e4-9039-b3edcbc83a16.png)

Save again, and the tags are merged into a single tag.

**Comment by darmens** [comment]
Were you able to reproduce it as well (more like "as bad") or it's just me?

**Comment by darmens** [comment]
This is due to an act_as_taggable_on security update: https://github.com/mbleigh/acts-as-taggable-on/issues/620

**Comment by parndt** [comment]
Fixed by #463
