### ISSUE TITLE
Override blog views and documentation

### ISSUE THREAD

**Issue by simanchen** [refinery/refinerycms-blog#440]
Hi,

I would like to know if there is any way to override the blog index view and the post item view to have more flexibility, if yes how to do this.

By the way is there somewhere more documentation of how to use this extension ? I googled it for a long time and can't find any documentation, for example to set up the number of posts displayed on the blog index page etc

It is quite urgent...Thank you in advance for your help

Best regards

**Comment by parndt** [comment]
If you mean the admin index:

rake refinery:override view=refinery/blog/admin/posts/index

if you mean the front end:

rake refinery:override view=refinery/blog/posts/index

**Comment by simanchen** [comment]
Thank you partndt for your answer, it worked, actually I tried rake refinery:override view=refinery/blog/* that's why it didn't work

However I have another question, when I try to apply another layout template to the Blog page it doesn't work, the Blog page still takes the template "application", I tested with a test page it worked I can select a specific template for the test page and not for Blog, is there a solution for this ?

By the way is there some documentation for the Blog extension ?

Thank you again !

**Comment by parndt** [comment]
I don't believe that the blog extension makes use of page templates (in other words, it ignores them and uses its own rendering - you can see which template it renders by reading the development logs as you load the page)
