### ISSUE TITLE
Cannot use blog_post_path in Views

### ISSUE THREAD

**Issue by lucianosousa** [refinery/refinerycms-blog#451]
Whats happen with the routes?
Why it's not available in the views? There is a specific reason?

I want to configure the comments with facebook and need access to the `url_for` or `blog_post_path` and these routes are not accessible:

I want to do something like this:
```
<div class="fb-comments" data-href="<%= blog_post_path(id: id) %>" data-numposts="5"></div>
```

**Comment by lucianosousa** [comment]
found it with:
```
Refinery::Core::Engine.routes.url_helpers.blog_post_path
```

**Comment by bricesanchez** [comment]
@lucianosousa you should probably do this : 
```ruby
<div class="fb-comments" data-href="<%= refinery.blog_post_path(post.id) %>" data-numposts="5"></div>
```

**Comment by lucianosousa** [comment]
@bricesanchez update:

I did:

```
<div class="fb-comments" data-href="<%= refinery.blog_post_url(@post) %>" data-numposts="5"></div>
```

it needs _url on the method to works properly with facebook comments.

Later, I'll improve this passing the @post as local variable, but, I'll inside the generators of the CMS ;)

Thanks for the tip.
