### ISSUE TITLE
FactoryGirl fails when trying to create :refinery_user as part of creating a :blog_post

### ISSUE THREAD

**Issue by charlesdeb** [refinery/refinerycms-blog#454]
The factory for blog_posts, has the following line it

    author { FactoryGirl.create(:refinery_user) }

which fails when I call `FactoryGirl.create(:blog_post)` in my own specs - because it references the :refinery_user factory on the author attribute. I can find no reference for a `:refinery_user` factory through refinery 3.0 but a quick look through the source would suggest to me that now that Devise has been decoupled from Refinery, the line should be more like:

     author { FactoryGirl.create(:authentication_devise_refinery_user) }

However, I also see that this `:refinery_user is used in a few specs in the blogging engine... and presumably your tests pass - otherwise you wouldn't have released this code. Suggestions?

**Comment by bricesanchez** [comment]
refinerycms-blog 3.0 is not yet released on Rubygems due to couple problems with Devise and fail CI.

It will be great if you could provide bug fixes :)

**Comment by charlesdeb** [comment]
I have worked around it in my own code by specifying the author when i create a blog post. So, 

    FactoryGirl.create(:blog_post)

now becomes:

    author = Refinery::Authentication::Devise::User.new
    FactoryGirl.create(:blog_post, author: author)

But that not very pretty and doesn't solve the real issue in the plugin. Would I be right in assuming that a real bug fix in the plugin would be more like what I suggest above? I'm guessing I would need to fork it, make the change, and then try and run your rspec tests over the whole plugin to verify I haven't broken anything. And if so, send you a pull request? I haven't submitted anything much more significant than typo fixes to refinery in the past.

**Comment by bricesanchez** [comment]
Fixed https://github.com/refinery/refinerycms-blog/pull/458
Thanks!
