### ISSUE TITLE
Seeds is outdated

### ISSUE THREAD

**Issue by sintro** [refinery/refinerycms-blog#460]
There is method in seeds.rb (https://github.com/refinery/refinerycms-blog/blob/master/db/seeds.rb) which creates the page parts for Blog page:
```
page.parts.create(:title => default_page_part, :body => nil, :position => index)
```
After this line does its job we get the page parts with titles like "{:title=>"Body", :slug=>"body"}" and "{:title=>"Side Body", :slug=>"side_body"}"
In refinerycmd-news extension this method is implemented something like this:
```
page.parts.create(title: default_page_part[:title], slug: default_page_part[:slug], body: nil, :position => index)
```

**Comment by bricesanchez** [comment]
Fixed, Thanks @sintro!
