### ISSUE TITLE
rubygems version is much out of date

### ISSUE THREAD

**Issue by NicholasKirchner** [refinery/refinerycms-blog#465]
After installing refinerycms and creating a new default project, the following line appears in the Gemfile:

`#  gem 'refinerycms-blog', ['~> 3.0', '>= 3.0.0']`

The latest version of refinerycms-blog on rubygems is 2.1.0, from October of 2013 (https://rubygems.org/gems/refinerycms-blog/).  Perhaps it's time for an update?

**Comment by bricesanchez** [comment]
Hello @NicholasKirchner, 

We have a blocker to release the 3.0.0 version: https://github.com/refinery/refinerycms-blog/pull/459

Help will be really appreciated :)

**Comment by NicholasKirchner** [comment]
Roger that.  PR coming before end of weekend.

**Comment by NicholasKirchner** [comment]
Where are things at with putting a version 3 on rubygems?

**Comment by bricesanchez** [comment]
refinerycms-blog 3.x was released on rubygems: https://rubygems.org/gems/refinerycms-blog
