### ISSUE TITLE
Error when trying to upgrade

### ISSUE THREAD

**Issue by matthewford** [refinery/refinerycms-blog#474]
Has anyone seen this error when trying to upgrade?

```
NameError (undefined local variable or method `slug' for <Refinery::PagePart:0x007fae7495b080>):

gem 'friendly_id', '~>5.1.0'
# Refinery CMS
gem 'refinerycms', '~> 3.0.0'
gem 'refinerycms-core', '~> 3.0.0'
gem 'refinerycms-blog', git: 'https://github.com/refinery/refinerycms-blog', branch: 'bugfix/decoupling'
```

**Comment by bricesanchez** [comment]
`gem 'refinerycms-blog', git: 'https://github.com/refinery/refinerycms-blog', branch: 'bugfix/decoupling'`

This branch should not be used, please use this branch for `gem 'refinerycms', '~> 3.0.0'` : 

`gem 'refinerycms-blog', git: 'https://github.com/refinery/refinerycms-blog', branch: '3-0-stable'`
