### ISSUE TITLE
Compatibility with Rails 5.2

### ISSUE THREAD

**Issue by Obi-TOB** [refinery/refinerycms-blog#488]
I'm using Refinery in conjunction with Spree 3.6, i.e. Rails 5.2.

The blog module is not yet Rails 5.2 ready as the globalize gem has no Rails 5.2 ready release yet.

Manual workaround for the time being is
- removing the dependency in gemspec
- including the globalize gem, master branch in the project's gemfile

Once globalize has a new release dependency should be updated. See as well
https://github.com/globalize/globalize/issues/696

Ok, I see that here is a full migration ongoing to include Mobility.
I guess this can be closed then.

**Comment by bricesanchez** [comment]
Hi @Obi-TOB !

We could safely remove the dependency to Globalize, this gem should not have this dependency and should be updated to Mobility.

**Comment by bricesanchez** [comment]
Hi @wbotelhos !

Moving to Mobility is a really great experience, no major issues, future proof. I'm already using it on production.

**Comment by wbotelhos** [comment]
Last week I moved on either.
I'm very satisfied. Thanks!
