### ISSUE TITLE
Log production

### ISSUE THREAD

**Issue by TonhaoSantos** [refinery/refinerycms-blog#493]
Is there any production log configuration?

**Comment by parndt** [comment]
@TonhaoSantos it should be the same as Rails logging configuration

**Comment by TonhaoSantos** [comment]
Thank you, I'll check.

**Comment by TonhaoSantos** [comment]
In my case Refinery is recording in the log the content of the pages.

**Comment by parndt** [comment]
Ah - that's quite possibly the input sanitiser that @bricesanchez put in https://github.com/refinery/refinerycms/pull/3117

**Comment by TonhaoSantos** [comment]
Tks
