### ISSUE TITLE
Bundle take too loog time to work.

### ISSUE THREAD

**Issue by lanzhiheng** [refinery/refinerycms-blog#495]
```
Fetching https://github.com/refinery/refinerycms
The dependency activerecord-jdbcsqlite3-adapter (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency activerecord-jdbcmysql-adapter (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency jdbc-mysql (= 5.1.13) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
The dependency activerecord-jdbcpostgresql-adapter (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for java. To add those platforms to the bundle, run `bundle lock --add-platform java`.
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies........................................................................................................^C
```

Hi, I want to send the PR for this project. So the first thing I want to do is running the test. But I can not `bundle install` successfully. Anyone encounter this issue?

**Comment by bricesanchez** [comment]
Hi @lanzhiheng, it should bundle as fast as your internet bandwith.

Could you give more informations to track the issue?

Thanks!

**Comment by lanzhiheng** [comment]
@bricesanchez I am sorry that I do not have any more information. Because the process block in this message 

```
Resolving dependencies........................................................
``` 

But the bundle process work fine in my others ruby project. Do you have the same issue when you run `bundle install ` in this project?  I clone the `refinerycms` repo to my computer just now, and the bundle process pass quickly
![image](https://user-images.githubusercontent.com/8858472/48564172-dc635700-e930-11e8-9e5a-078fd610f163.png)

but the bundle not work in this project.

**Comment by lanzhiheng** [comment]
@bricesanchez 

It is amazing that after I remove **gemspec** in `Gemfile` I can pass the bundle very quickly. But I can not pass it with **gemspec** statement.

**Comment by lanzhiheng** [comment]
I have resolved this issue, I closed it.
